### ISSUE TITLE
无法在Linux下执行

### ISSUE THREAD

**Issue by shop668** [manyeyes/AliParaformerAsr#1]
你好，感谢您的分享不过我发现它无法在Linux下执行，是因为使用的KaldiNativeFbankSharp中的kaldi-native-fbank-dll只有Windows的，错误如下：
2023-07-08 13:26:10.353900878 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer '8351'. It is not used by any node and should be removed from the model.
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'kaldi-native-fbank' or one of its dependencies. In order to help diagnose loading problems, consider setting the ronment variable: libkaldi-native-fbank: cannot open shared object file: No such file or directory
   at KaldiNativeFbankSharp.DLL.KaldiNativeFbank.GetFbankOptions(Single dither, Boolean snip_edges, Single sample_rate, Int32 num_bins, Single frame_shift, Single frame_length, Single energy_floebug_mel, String window_type)
   at KaldiNativeFbankSharp.OnlineFbank..ctor(Single dither, Boolean snip_edges, Single sample_rate, Int32 num_bins)
   at AliParaformerAsr.WavFrontend..ctor(String mvnFilePath, FrontendConfEntity frontendConfEntity) in D:\Develop\AliParaformerAsr-master\AliParaformerAsr-master\AliParaformerAsr\WavFrontend.cs:
   at AliParaformerAsr.OfflineRecognizer..ctor(String modelFilePath, String configFilePath, String mvnFilePath, String tokensFilePath, Int32 batchSize, Int32 threadsNum) in D:\Develop\AliParafor\AliParaformerAsr-master\AliParaformerAsr\OfflineRecognizer.cs:line 42
   at Program.Main() in D:\Develop\AliParaformerAsr-master\AliParaformerAsr-master\AliParaformerAsr.Examples\Program.cs:line 13
已放弃 (核心已转储)

再次感谢分享

**Comment by csukuangfj** [comment]
建议参考sherpa-onnx 或者PortAudioSharp2 进行封装

**Comment by manyeyes** [comment]
预计下周，争取解决，感谢

**Comment by manyeyes** [comment]
solve：
Update KaldiNativeFbankSharp to 1.0.2 to support linux-x64 and osx.10.14-x64
@csukuangfj @shop668
